from django.urls import path
from django.views import generic

from . import views
from . import models

urlpatterns = [
    path('', generic.TemplateView.as_view(template_name='home.html'), name='home'),
    path(
        'locations',
        views.locations,
        name='locations'
    ),
    path(
        'edit_location/<int:id>',
        views.edit_location,
        name='edit_location'
    ),
    path(
        'view_location/<int:id>',
        views.view_location,
        name='view_location'
    ),
    path(
        'update_location/<int:id>',
        views.update_location,
        name='update_location'
    ),
    path(
        'delete_location/<int:id>',
        views.delete_location,
        name='delete_location'
    ),
    path(
        'create_location',
        generic.TemplateView.as_view(template_name='partials/create_location.html'),
        name='create_location'
    ),
    path(
        'save_new_location',
        views.save_new_location,
        name='save_new_location'
    ),
    path(
        'location_list',
        generic.ListView.as_view(
            model=models.Location,
        )
    ),
    path(
        'dinosaur_chart',
        views.dinosaur_chart,
        name='dinosaur_chart'
    ),
    path(
        'dinosaur_chart_partial',
        views.dinosaur_chart_partial,
        name='dinosaur_chart_partial'
    ),
    path(
        'dinosaurs',
        views.dinosaurs,
        name='dinosaurs'
    ),
    path(
        'update_dinosaurs_from_selection',
        views.update_dinosaurs_from_selection,
        name='update_dinosaurs_from_selection'
    ),
    path(
        'dinosearch',
        views.dinosearch,
        name='dinosearch'
    ),
    path(
        'dinosearch_list',
        views.dinosearch_list,
        name='dinosearch_list'
    ),
    path(
        'scrolling_dinosaur_list',
        generic.TemplateView.as_view(
            template_name='scrolling_dinosaur_list.html'
        ),
        name='scrolling_dinosaur_list'
    ),
    path(
        'dinosaur_page_list/<int:page_number>',
        views.dinosaur_list_next_10,
        name='dinosaur_page_list'
    ),
    path(
        'dinosaur_favourites',
        views.dinosaur_favourites,
        name='dinosaur_favourites'
    ),
    path(
        'update_dinosaur_favourites',
        views.update_dinosaur_favourites,
        name='update_dinosaur_favourites'
    ),
    path(
        'dinosaurs_by_diet',
        views.dinosaurs_by_diet,
        name='dinosaurs_by_diet'
    ),
    path(
        'set_dinosaurs_for_diet',
        views.set_dinosaurs_for_diet,
        name='set_dinosaurs_for_diet'
    ),
    path(
        'about',
        generic.TemplateView.as_view(
            template_name='about.html'
        ),
        name='about'
    ),
    path(
        'dinosaurs_by_period',
        generic.TemplateView.as_view(
            template_name='dinosaurs_by_period.html',
            extra_context=dict(
                dinosaurs=models.Dinosaur.objects.order_by('name'),
                periods=models.Period.objects.order_by('name')
            )
        ),
        name='dinosaurs_by_period'
    ),
    path(
        'dinosaurs_for_period',
        views.dinosaurs_for_period,
        name='dinosaurs_for_period'
    ),
]
