# Generated by Django 4.1.5 on 2023-02-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinosaurs.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('period_start', models.IntegerField(null=True)),
                ('period_end', models.IntegerField(null=True)),
                ('length_in_cms', models.IntegerField(null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('diet', models.ManyToManyField(to='dinosaurs.diet')),
                ('lived_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dinosaurs.location')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dinosaurs.period')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dinosaurs.species')),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dinosaurs.taxon')),
            ],
        ),
    ]
